# Generated by Django 6.0 on 2025-12-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('lon', models.FloatField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='core_fuelst_state_e7c819_idx'), models.Index(fields=['lat', 'lon'], name='core_fuelst_lat_1126f8_idx')],
            },
        ),
    ]
